
services:
  # ==============================================
  # REDIS - Cache e Comunicação entre Serviços
  # ==============================================
  redis:
    image: redis:7-alpine
    container_name: famagpt_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - famagpt_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # ==============================================
  # ORCHESTRATOR - LangGraph Core
  # ==============================================
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: famagpt_orchestrator
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=orchestrator
      - PORT=8000
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    depends_on:
      - redis
      - database
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro

  # ==============================================
  # WEBHOOKS - WhatsApp Integration
  # ==============================================
  webhooks:
    build:
      context: ./webhooks
      dockerfile: Dockerfile
    container_name: famagpt_webhooks
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=webhooks
      - PORT=8001
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - ORCHESTRATOR_URL=http://orchestrator:8000
    depends_on:
      - redis
      - database
      - orchestrator
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro

  # ==============================================
  # TRANSCRIPTION - Audio to Text
  # ==============================================
  transcription:
    build:
      context: ./transcription
      dockerfile: Dockerfile
    container_name: famagpt_transcription
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=transcription
      - PORT=8002
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
    depends_on:
      - redis
      - database
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro
      - transcription_temp:/app/temp

  # ==============================================
  # WEB_SEARCH - Property Search
  # ==============================================
  web_search:
    build:
      context: ./web_search
      dockerfile: Dockerfile
    container_name: famagpt_web_search
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=web_search
      - PORT=8003
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - PLAYWRIGHT_BROWSERS_PATH=/app/browsers
    depends_on:
      - redis
      - database
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro
      - playwright_browsers:/app/browsers

  # ==============================================
  # MEMORY - Hybrid Memory System
  # ==============================================
  memory:
    build:
      context: ./memory
      dockerfile: Dockerfile
    container_name: famagpt_memory
    restart: unless-stopped
    ports:
      - "8004:8004"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=memory
      - PORT=8004
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - database
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro

  # ==============================================
  # RAG - Retrieval Augmented Generation
  # ==============================================
  rag:
    build:
      context: ./rag
      dockerfile: Dockerfile
    container_name: famagpt_rag
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=rag
      - PORT=8005
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
    depends_on:
      - redis
      - database
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro
      - rag_documents:/app/documents

  # ==============================================
  # DATABASE - Database Service
  # ==============================================
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: famagpt_database
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=database
      - PORT=8006
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro

  # ==============================================
  # SPECIALIST - Real Estate Agent
  # ==============================================
  specialist:
    build:
      context: ./specialist
      dockerfile: Dockerfile
    container_name: famagpt_specialist
    restart: unless-stopped
    ports:
      - "8007:8007"
    environment:
      - PYTHONPATH=/app
      - SERVICE_NAME=specialist
      - PORT=8007
      - REDIS_URL=redis://redis:6379
      - DATABASE_SERVICE_URL=http://database:8006
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEMORY_URL=http://memory:8004
      - RAG_URL=http://rag:8005
      - WEB_SEARCH_URL=http://web_search:8003
    depends_on:
      - redis
      - database
      - memory
      - rag
      - web_search
    networks:
      - famagpt_network
    volumes:
      - ./shared:/app/shared:ro

# ==============================================
# NETWORKS
# ==============================================
networks:
  famagpt_network:
    driver: bridge

# ==============================================
# VOLUMES
# ==============================================
volumes:
  redis_data:
  transcription_temp:
  playwright_browsers:
  rag_documents:
