# FamaGPT Centralized Configuration
# Version: 1.0 - Q4 2025 Infrastructure Hardening

# Global Settings
global:
  project_name: "FamaGPT"
  version: "1.0.0"
  environment: "${ENVIRONMENT:-development}"
  debug: "${DEBUG:-false}"
  log_level: "${LOG_LEVEL:-INFO}"

# Service Configuration
services:
  orchestrator:
    name: "orchestrator"
    port: 8000
    host: "0.0.0.0"

    # Rate Limiting
    rate_limiting:
      enabled: "${RATE_LIMIT_ENABLED:-true}"
      requests_per_minute: "${RATE_LIMIT_RPM:-100}"
      burst_allowance: "${RATE_LIMIT_BURST:-20}"
      cost_limit_brl_per_day: "${COST_LIMIT_BRL_DAY:-500.0}"

      # OpenAI Specific
      openai_requests_per_minute: 60
      openai_estimated_cost_per_request_brl: 0.50

    # Observability
    observability:
      metrics_enabled: true
      tracing_enabled: "${LANGCHAIN_TRACING_V2:-true}"
      langsmith_project: "${LANGCHAIN_PROJECT:-famagpt-orchestrator}"

    # Timeouts & Retries
    timeouts:
      default_timeout_seconds: 30
      openai_timeout_seconds: 45
      redis_timeout_seconds: 5
      database_timeout_seconds: 10

    retries:
      default_max_attempts: 3
      exponential_backoff_base: 2
      max_backoff_seconds: 60

  webhooks:
    name: "webhooks"
    port: 8001

    rate_limiting:
      enabled: true
      requests_per_minute: 200  # Higher for webhook bursts
      burst_allowance: 50

  transcription:
    name: "transcription"
    port: 8002

    rate_limiting:
      enabled: true
      requests_per_minute: 30   # Audio processing is expensive
      burst_allowance: 5

    processing:
      max_file_size_mb: 25
      supported_formats: ["mp3", "wav", "m4a", "ogg"]
      whisper_model: "${WHISPER_MODEL:-base}"

  web_search:
    name: "web_search"
    port: 8003

    rate_limiting:
      enabled: true
      requests_per_minute: 50   # Scraping rate limits
      burst_allowance: 10

    scraping:
      max_pages_per_request: 5
      request_delay_seconds: 1
      user_agent: "FamaGPT/1.0 PropertyBot"

  memory:
    name: "memory"
    port: 8004

    rate_limiting:
      enabled: true
      requests_per_minute: 150
      burst_allowance: 30

  rag:
    name: "rag"
    port: 8005

    rate_limiting:
      enabled: true
      requests_per_minute: 80
      burst_allowance: 15

    embeddings:
      model: "${EMBEDDING_MODEL:-text-embedding-3-small}"
      chunk_size: 1000
      chunk_overlap: 200

  database:
    name: "database"
    port: 8006

    rate_limiting:
      enabled: true
      requests_per_minute: 300  # High for internal service
      burst_allowance: 50

  specialist:
    name: "specialist"
    port: 8007

    rate_limiting:
      enabled: true
      requests_per_minute: 60
      burst_allowance: 15

# Infrastructure Configuration
infrastructure:
  redis:
    url: "${REDIS_URL:-redis://redis:6379}"
    connection_pool:
      max_connections: 20
      retry_on_timeout: true
      socket_connect_timeout: 5
      socket_timeout: 5

  database:
    url: "${DATABASE_URL}"
    service_url: "${DATABASE_SERVICE_URL:-http://database:8006}"

  external_apis:
    openai:
      api_key: "${OPENAI_API_KEY}"
      base_url: "https://api.openai.com/v1"
      timeout_seconds: 45
      max_retries: 3

    evolution:
      api_key: "${EVOLUTION_API_KEY}"
      api_url: "${EVOLUTION_API_URL}"
      webhook_secret: "${WEBHOOK_SECRET}"

    langsmith:
      api_key: "${LANGCHAIN_API_KEY}"
      tracing_enabled: "${LANGCHAIN_TRACING_V2:-true}"
      project: "${LANGCHAIN_PROJECT:-famagpt}"

# Monitoring & Alerting
monitoring:
  health_checks:
    enabled: true
    interval_seconds: 30
    timeout_seconds: 5

  metrics:
    enabled: true
    prometheus_port: 9090

    # Critical metrics thresholds
    thresholds:
      response_time_p95_seconds: 2.5
      error_rate_percent: 0.05
      uptime_percent: 99.99
      cost_utilization_percent: 80

  alerting:
    enabled: true

    rules:
      - name: "high_error_rate"
        condition: "error_rate > 0.1"
        severity: "critical"

      - name: "high_response_time"
        condition: "response_time_p95 > 3.0"
        severity: "warning"

      - name: "cost_limit_approaching"
        condition: "daily_cost_utilization > 0.8"
        severity: "warning"

      - name: "rate_limit_exhausted"
        condition: "rate_limit_rejections > 10"
        severity: "warning"

# Security Configuration
security:
  cors:
    enabled: true
    allowed_origins: "${ALLOWED_ORIGINS:-*}"
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true

  api_keys:
    rotation_enabled: false  # TODO: Implement in future sprints
    validation_enabled: true

  internal_communication:
    require_auth: false  # TODO: Implement mTLS in future sprints

# Business Logic Configuration
business:
  target_market:
    city: "Uberlândia"
    state: "MG"
    search_radius_km: 50

  features:
    b2b_corretor_mode: true
    analytics_enabled: true
    crm_integration_enabled: false  # Future feature

  quotas:
    max_corretores: 300
    messages_per_corretor_per_day: 50
    cost_per_corretor_per_month_brl: 147